name: flutter_notebook_chapter_41
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  hugeicons: ^0.0.7
  gap: ^3.0.1
  percent_indicator: ^4.2.4
  go_router: ^14.6.2
  ticket_widget: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
